name: linux_build

on:  [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install depends
      run: |
        sudo apt update
        sudo apt install -qq -y libssl* libevent* openssl*
    - name: Build
      run: make ENABLE_STATIC=true  DISABLE_SHADOWSOCKS=true
    - name: F
      run: ls -lah gen
