name: linux_build

on:  
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install depends
      run: |
        sudo apt update
        sudo apt install -qq -y libssl* libevent*
    - name: Build
      run: make ENABLE_STATIC=true USE_CRYPTO_POLARSSL=true  DISABLE_SHADOWSOCKS=true
    - name: F
      run: ls -lah
