name: linux_build

on:  [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install depends
      run: |
        sudo apt update
        sudo apt install -qq -y libssl* libevent* openssl*
    - name: Build
      run: make ENABLE_STATIC=true  DISABLE_SHADOWSOCKS=true
    - name: Pack
      run: tar -czf /tmp/redsocks.tar.gz . && cp /tmp/redsocks.tar.gz .
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
          name: redsocks.tar.gz
          path: redsocks.tar.gz
